name: agentic-pipelines-env
channels:
  - conda-forge
  - bioconda
dependencies:
  - python==3.10
  - pandas
  - ipykernel
  - ipywidgets
  - jupyter
  - pydantic-ai==0.2.4
  - python-dotenv
  - rich
  - snakemake
  - pip
  - pip:
    - scikit-learn
    - wandb
    - hrid # ??
    - timeout-function-decorator # ??
    - pydantic-ai-slim[openai]